imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ['127.0.0.1']
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: tls
    port:  587

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Fango\UserBundle\Entity\User
    from_email:
        address: noreply@fango.me
        sender_name: Fango.me
    service:
        user_manager: fango_user.user_manager
    registration:
        form:
            type: fango_user_registration
    resetting:
        token_ttl: 86400
        email:
            template: FOSUserBundle:Resetting:email.txt.twig

seferov_deployer:
    servers:
        production:
            connection:
                host: fango.me
                username: root
                password: %server_password%
            git: 'git@bitbucket.org:seferov/fango.git'

hip_mandrill:
    api_key: 5xkvD0TiNAfL4AAbZXxWeQ
#    disable_delivery: true # useful for dev/test environment. Default value is 'false'
    default:
        sender: hello@fango.me
        sender_name: Fango.me

bazinga_geocoder:
    providers:
        data_science_toolkit: ~
        ip_info_db:
            api_key: 7515964f3c60f38933aa380b905d1904d6d4c970da02865029ffb1842528bd6a

seferov_aws:
    key: AKIAIBQSD3VAZPDOVCKQ
    secret: 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
    region: us-west-2

snc_redis:
    clients:
        crawler:
            type: predis
            alias: crawler
            dsn: redis://localhost/1

seferov_mailer:
    main_route: fango_main_homepage

ekino_new_relic:
    enabled: true
    application_name: Fango
    deployment_names: ~
    api_key: 9f900b28dcf0caf92f3a2115cf4743d1402db7cdcd3f9ea
    license_key: ab9e90d189481a430798992d8c7a76bebcd3f9ea
    xmit: false
    logging: false
    instrument: false
    log_exceptions: true
    log_commands: true
    using_symfony_cache: false
    transaction_naming: route
    transaction_naming_service: ~
    ignored_routes: []
    ignored_paths: []
    ignored_commands: []