fango_main:
    resource: "@FangoMainBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fango_user:
    resource: "@FangoUserBundle/Resources/config/routing.yml"
    prefix:   /
