fango_adjustio:
    resource: "@FangoAdjustioBundle/Resources/config/routing.yml"
    prefix:   /

seferov_mailer:
    resource: "@SeferovMailerBundle/Resources/config/routing.yml"
    prefix:   /

fango_mail:
    resource: "@FangoMailBundle/Resources/config/routing.yml"
    prefix:   /

fango_main:
    resource: "@FangoMainBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fango_user:
    resource: "@FangoUserBundle/Resources/config/routing.yml"
    prefix:   /
