Fango\MainBundle\Entity\Campaign:
    type: entity
    table: fg_campaign
    repositoryClass: Fango\MainBundle\Entity\CampaignRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:         { type: string, length: 255 }
        logo:         { type: string, length: 255, nullable: true }
        description:  { type: text, nullable: true }
        actionLink:   { type: string, length: 255, column: action_link }
        previewLink:  { type: string, length: 255, column: preview_link }
        cpa:          { type: float, nullable: true }
        status:       { type: string, length: 15, nullable: true }
        socialText:   { type: string, length: 140, nullable: true, column: social_text }
    oneToMany:
        userCampaigns:
            targetEntity: Fango\MainBundle\Entity\UserCampaign
            mappedBy: campaign
        countries:
            targetEntity: Fango\MainBundle\Entity\CampaignCountry
            mappedBy: campaign
    lifecycleCallbacks: {  }
