Fango\MainBundle\Entity\Transaction:
    type: entity
    table: fg_transaction
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        hash:
            type: string
            length: 255
        country:
            type: string
            lenght: 5
            nullable: true
        ipAddress:
            type: string
            length: '50'
            column: ip_address
        referer:
            type: string
            length: 255
            nullable: true
        action:
            type: boolean
        createdAt:
            type: datetime
            column: created_at
        userAgent:
            type: string
            length: 255
            column: user_agent
            nullable: true
        disabled:
            type: boolean
            nullable: true
    manyToOne:
        userCampaign:
            targetEntity: Fango\MainBundle\Entity\UserCampaign
            inversedBy: transactions
            joinColumn:
                name: user_campaign_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
