Fango\UserBundle\Entity\Network:
    type: entity
    table: fg_user_network
    repositoryClass: Fango\UserBundle\Entity\NetworkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:           { type: string, length: '50' }
        networkId:      { type: string, column: network_id, length: 100 }
        display:        { type: string, length: 100, nullable: true }
        createdAt:      { type: datetime, column: created_at }
        followersCount: { type: bigint, column: followers_count, nullable: true }
        rest:           { type: text, nullable: true }
        token:          { type: string, length: 255, column: token, nullable: true }
        tokenSecret:    { type: string, length: 255, column: token_secret, nullable: true }
        cppDay:         { type: string, length: 7, column: cpp_day, nullable: true }
        cppWeek:        { type: string, length: 7, column: cpp_week, nullable: true }
        cppLifetime:    { type: string, length: 7, column: cpp_lifetime, nullable: true }
    manyToOne:
        user:
            targetEntity: Fango\UserBundle\Entity\User
            inversedBy: networks
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
